language: c
dist: focal
addons:
  apt:
    packages:
      - clang
      - clang-tools
      - cmake
      - libc++-dev
      - libc++abi1
      - libglfw3-dev
      - libglu1-mesa-dev
      - libopengl-dev
      - libunwind-dev
      - libunwind8
      - libxrandr
      - lld
script:
  - make
  - env TOOL=cmake make
