addons:
  apt:
    packages:
      - clang
      - clang-tools
      - cmake
      - libc++-dev
      - libc++abi1
      - libglfw3-dev
      - libglu1-mesa-dev
      - libopengl-dev
      - libunwind-dev
      - libunwind8
      - libxcursor-dev
      - libxcursor1
      - libxi-dev
      - libxi6
      - libxinerama-dev
      - libxinerama1
      - libxrandr-dev
      - libxrandr2
      - lld
dist: focal
env:
  matrix:
    - TOOL=cmake
    - TOOL=make
language: c
notifications:
  email: false
os:
  - linux
script:
  - env TOOL=$TOOL make
